#! /bin/bash


# Usage: build_describe
# Display description for this command wrapper.
build_describe() {
    echo "Build all the images of the OpenXT project using bitbake."
}

build_need_conf() { return 0; }

# Usage: build [mode]
# Build all the images of the OpenXT project using bitbake using the
# build-manifest file in CONF_DIR.
# modes:
#   clean: Run "cleanall" on the image recipe before building it.
build_main() {
    local mode=$1

    pushd "${TOP}/${BUILD_DIR}" >/dev/null

    # Source build_env to get access to necessary OE variables.
    . "${TOP}/${BUILD_DIR}/build_env"

    # Overwrite the build timestamp.
    echo "OPENXT_BUILD_DATE=\"$(date '+%T %D')\"" > ${CONF_DIR}/openxt-build-date.conf

    while read l ; do
        if [ -z "${l%%#*}" ]; then
            continue
        fi

        local entry=(${l})
        local image="${entry[0]}"
        local env="${entry[@]:1}"

        if [ "${mode}" = "clean" ]; then
            eval ${env} bitbake -c cleanall "${image}"
        fi
        if ! eval ${env} bitbake "${image}" ; then
            echo "${env} bitbake \"${image}\" failed." >&2
            return 1
        fi

    done < "${CONF_DIR}/build-manifest"

    popd >/dev/null
}
