#! /bin/bash

# Usage: deploy_iso_legacy
# Run the required staging steps and generate the ISO image.
deploy_iso_legacy() {
    # TODO: This could be defined from configuration.
    local iso_name="openxt-installer.iso"
    local iso_path="${DEPLOY_DIR}/${iso_name}"

    # Prepare repository layout and write XC-{PACKAGE,REPOSITORY,SIGNATURE}
    # meta files.
    call_cmd "stage" "repository"
    # Prepare ISO image layout.
    # TODO: Amend syslinux files to reflect versions & such
    call_cmd "stage" "iso-old"

    genisoimage -o "${iso_path}" \
        -b "isolinux/isolinux.bin" -c "isolinux/boot.cat" \
        -no-emul-boot \
        -boot-load-size 4 \
        -boot-info-table \
        -r -J -l -V "OpenXT ${OPENXT_VERSION} installer." \
        "${STAGING_DIR}/iso" \
        "${STAGING_DIR}/repository"
    if [ $? -ne 0 ]; then
        echo "genisoimage failed."
        return 1
    fi

    ${STAGING_DIR}/iso/isolinux/isohybrid ${iso_path}
    if [ $? -ne 0 ]; then
        echo "isohybrid failed."
        return 1
    fi
}

# Usage: deploy_iso
# Run the required staging steps and generate the ISO image.
deploy_iso() {
    # TODO: This could be defined from configuration.
    local iso_name="openxt-installer.iso"
    local iso_path="${DEPLOY_DIR}/${iso_name}"
    local sys_sanity=0

    if ! command_sane "xorriso" "libisoburn"; then
        return 1
    fi

    # Prepare repository layout and write XC-{PACKAGE,REPOSITORY,SIGNATURE}
    # meta files.
    call_cmd "stage" "repository"
    # Prepare ISO image layout.
    # TODO: Amend syslinux files to reflect versions & such
    call_cmd "stage" "iso"

    xorriso -as mkisofs \
        -o "${iso_path}" \
        -isohybrid-mbr "${STAGING_DIR}/iso/isolinux/isohdpfx.bin" \
        -c "isolinux/boot.cat" \
        -b "isolinux/isolinux.bin" \
        -no-emul-boot \
        -boot-load-size 4 \
        -boot-info-table \
        -eltorito-alt-boot \
        -e "isolinux/efiboot.img" \
        -no-emul-boot \
        -isohybrid-gpt-basdat \
        -r \
        -J \
        -l \
        -V "OpenXT ${OPENXT_VERSION} installer." \
        -f \
        -quiet \
        "${STAGING_DIR}/iso" \
        "${STAGING_DIR}/repository"
}

deploy_pxe_usage() {
    local rc="$1"
    echo "Usage: ./openxt.sh deploy pxe [-r [<repo-user>@]<repo-server>:<repo-path>] [<tftp-user>@]<tftp-server>:<tftp-path> <repository-uri>"
    echo "  -r  rsync repository files to http(s) server passed as argument, [<repo-user>@]<repo-server>:<repo-path>."
    exit "${rc}"
}

__deploy_pxe() {
    local pxe_staging="${STAGING_DIR}/pxe"
    local repo_dst=""

    # Prepare repository layout and write XC-{PACKAGE,REPOSITORY,SIGNATURE}
    # meta files.
    call_cmd "stage" "repository"

    while getopts "hr:" opt; do
        case "${opt}" in
            h) deploy_pxe_usage 0 ;;
            :) echo "Option \`${OPTARG}' is missing an argument." >&2
               deploy_pxe_usage 1 ;;
            \?) echo "Unknown option \`${OPTARG}'." >&2
                deploy_pxe_usage 1 ;;
            r) repo_dst="${OPTARG}" ;;
        esac
    done
    shift $((${OPTIND} - 1))

    if [ "$#" -ne 2 ]; then
        deploy_pxe_usage 1
    fi

    local tftp_dst="$1"
    local repo_url="$2"

    # TODO: Not great, will change staging data...
    #       Not too bad since we "stage pxe" again every time.
    local answer_files=()
    for ans in "${pxe_staging}"/*.ans; do
        sed -i "s|\(<source.\+>\).\+</source>|\1${repo_url}</source>|" "${ans}"
        answer_files+=("${ans}")
    done
    rsync -rlptDvzr "${pxe_staging}/" "${tftp_dst}"
    if [ -n "${repo_dst}" ]; then
        echo rsync -rlptDvzr "${STAGING_DIR}/repository/" ${answer_files[@]} "${repo_dst}"
        rsync -avzr "${STAGING_DIR}/repository/" ${answer_files[@]} "${repo_dst}"
    fi
}
deploy_pxe_legacy() {
    # Prepare PXE staging.
    call_cmd "stage" "pxe-old"

    __deploy_pxe $@
}
deploy_pxe() {
    # Prepare PXE staging.
    call_cmd "stage" "pxe"

    __deploy_pxe $@
}

# Usage: deploy_describe
# Display description for this command wrapper.
deploy_describe() {
    echo "Deploy OpenXT installer on an installation media."
}

deploy_dependecy() {
    echo "stage"
}

# Usage: deploy_usage
# Display usage for this command wrapper.
deploy_usage() {
    cat <<End-of-usage
Deployment command list:
    iso-old: Create a BIOS/MBR bootable ISO hybrid image of an OpenXT
             installer (can be dd'ed on a thumbdrive). This installer
             is available until OpenXT 7
        iso: Create an EFI bootable ISO hybrid image of an OpenXT
             installer (can be dd'ed on a thumbdrive). This installer
             is available starting with OpenXT 8
    pxe-old: Copy a PXE compatible OpenXT installer to the given
             [<tftp-user>@]<tftp-server>:<tftp-path> tftp server, and
             setup the installer to fetch repository from <repo-uri>
        pxe: Copy a PXE compatible OpenXT installer to the given
             [<tftp-user>@]<tftp-server>:<tftp-path> tftp server, and
             setup the installer to fetch repository from <repo-uri>
End-of-usage
    exit $1
}

deploy_need_conf() { return 0; }

# Usage: deploy <command>
# Deploy OpenXT on the selected installation media.
deploy_main() {
    target="$1"
    shift 1

    case "${target}" in
        "iso-old") check_cmd_version "${target}"
                   deploy_iso_legacy $@ ;;
        "iso") check_cmd_version "${target}"
               deploy_iso $@ ;;
        "pxe-old") deploy_pxe_legacy $@ ;;
        "pxe") deploy_pxe $@ ;;
        "help") deploy_usage 0 ;;
        *) echo "Unknown staging command \`${target}'." >&2
           deploy_usage 1
           ;;
    esac
}
